### ISSUE TITLE
Find a solution for ./genproto.sh

### ISSUE THREAD

**Issue by fjoniyz** [yamaceay/ratingservice#1]
As of now, if someone executes the command ./genproto.sh, the person will see the following error: 
```
protoc-gen-go: unable to determine Go import path for "demo.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
```
The first solution proposed(a "go_package" option) does not work anymore as of proto3(see [this](https://stackoverflow.com/questions/31801257/why-required-and-optional-is-removed-in-protocol-buffers-3)) thus another solution should be found in order to generate the file

**Comment by stano45** [comment]
SOLVED
